#goal location send to the action server
std_msgs/Bool translation # if enabled only, straight driving
std_msgs/Bool rotation    # if enabled only, in place turn
						  # if both enabled, will do  straight driving and then in place turn
geometry_msgs/Pose pose   # goal pose
---
#result 
bool reached
geometry_msgs/Pose pose   # return back the end pose so it can be used as new starting pose
---
#feedback 
geometry_msgs/Vector3 vector # show the distance to goal, x, y, and z is the rotation